#!/bin/bash

if [ $# = 0 ]; then
    FILE=`date '+%Y/%m/%d.md'`
else
    FILE=`date -v-$1d '+%Y/%m/%d.md'`
fi

FILE_DIR=$(cd $(dirname $0); pwd)
FULLPATH_FILE="$FILE_DIR/$FILE"

if [ ! -e "$FULLPATH_FILE" ]; then
    mkdir -p $FILE_DIR
    touch $FULLPATH_FILE
fi

open $FULLPATH_FILE
